name: githubaction-firstpipeline
on: [push]
run-name: test-pipline
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
    
      - name: this is first run
        env:
             MY_VAR: Hi there! My name is
             FIRST_NAME: Mona
             MIDDLE_NAME: The
             LAST_NAME: Octocat
        run: |
            echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      
  
